### ISSUE TITLE
Configure all api instances at a time

### ISSUE THREAD

**Issue by javierbrea** [XbyOrange/mercury-api#6]
When you have to configure many origins at a time with the same value (a very common scenario for "baseUrl", or authentication headers, for example), you have to import all desired origins and iterate over all calling to its "config" method.
This is really annoying because for each origin you use, you have to add the new dependency to your "configurator" piece, and you have to repeat this pattern in every applications.

It would be very useful to export a method for configuring or cleaning groups of `Api` instances at a time. (Maybe a system based on tags will be very flexible to allow configuring or cleaning only certain subgroups).

A proposal:

```js
import { Api } from "@xbyorange/mercury-api";

export const fooCollection = new Api("/foo-url", {
  tags: ["xbyorange-api",  "need-auth"]
})

export const fooPublicCollection = new Api("/foo-public-url", {
  tags: ["xbyorange-api"]
})

export const fooExternalApi  = new Api("/foo-url", {
  tags: ["external-api"]
})
```
Now, you can configure each api url separately:
```js
import { apis } from "@xbyorange/mercury-api"

apis.config("xbyorange-api", {
  baseUrl: "https://foo-url/api"
})

apis.config("external-api", {
  baseUrl: "https://foo-external-domain"
})
```
To configure authentication: 
```js
import { apis } from "@xbyorange/mercury-api"

export const setAuth = token => {
  apis.setHeaders("need-auth", {
    "Authorization": `Bearer ${token}`
  })
}
```

**Comment by javierbrea** [comment]
Another instance methods, such as `clean` and `setHeaders` should be exposed too to this utility:

```js
import { apis } from "@xbyorange/mercury-api"
apis.clean("xbyorange-api")
```

**Comment by manuelitox** [comment]
Sounds good! 

Another option could be:

```javascript
import { Api } from "@xbyorange/mercury-api";

const catalog = new Api('/catalog-api')
catalog.tags = ['external-api', 'internal-api']
```

I think this way could be more friendly when reading it.

What do you think?

**Comment by javierbrea** [comment]
@manuelitox I think it can be good idea to expose setters for configuration, if you prefer that syntax, but I think that then we should implement setters for all configuration properties, not only for the `tags` one.

Maybe it is better to open another issue related to this. Feel free if you agree ;)

**Comment by manuelitox** [comment]
Done! 

Issue: [Implement setters for all configurations and HTTP's request methods](https://github.com/XbyOrange/mercury-api/issues/7)
